### ISSUE TITLE
Invalid object vs null object

### ISSUE THREAD

**Issue by Julio-Guerra** [DataDog/libddwaf#14]
Make possible to call the WAF with:
1. A JSON like `{ "key": null }`
1. A native object like `{ "key": <a native value whose type cannot be represented into a WAF object> }`

For 1, for sure it means we need to introduce the null value representation in the current WAF format.
For 2, I'm unsure about using the null value as it looses the information "it wasn't null, but an unsupported value". The current invalid object could be possibly used for that.

But as of today, unsupported values imply the WAF flows gets aborted when they reach them, and even invalidates the previously matching flows (IIRC, to be confirmed). IMO, this makes useless to call the WAF when you have an invalid value somewhere in the object that will be checked by a flow. I would simplify this by either removing the invalid value, or making it useful for 2, without aborting the WAF flows when reached. To be further challenged with more use-cases.

Happy to give a hand if needed

**Comment by simon-id** [comment]
I will do as gustavo for now and serialize unsupported objects as empty maps.

**Comment by Anilm3** [comment]
https://github.com/DataDog/libddwaf/pull/77 provides **internal** support for invalid objects within containers (they are simply ignored), however this will only be available once we remove the validator.

**Comment by Anilm3** [comment]
This is available to some degree in `1.5.0-alpha0`, although perhaps I need to add a few more tests to cover this case. Generally invalid objects can now be used inside structures and won't cause the WAF to reject the input. If the invalid object is part of a map, its key will still be analysed if relevant, however its value will simply be ignored.

> 2. A native object like `{ "key": <a native value whose type cannot be represented into a WAF object> }`
> 
> ... For 2, I'm unsure about using the null value as it looses the information "it wasn't null, but an unsupported value". The current invalid object could be possibly used for that.

The distinction between `null` and `invalid` is not particularly meaningful to the WAF as there is no interest in knowing whether you could represent a value as a WAF object or not, so I think what I'll do is rename the `DDWAF_OBJ_INVALID` to `DDWAF_OBJ_NULL` at some point in the near future.

**Comment by Anilm3** [comment]
`null` type and proper `invalid` (and `null`) support within containers has been implemented in https://github.com/DataDog/libddwaf/pull/197
