### ISSUE TITLE
Stop returning JSON blobs

### ISSUE THREAD

**Issue by lloeki** [DataDog/libddwaf#19]
From @Julio-Guerra in https://github.com/DataDog/libddwaf/pull/12#issuecomment-939543323

> (And feel free to stop returning a json blob ;-p)

The libraries need to reach into the result, so this means there's a serialisation that gets deserialized right after. A JSON serializer will run again on the full event payload, and in the current case at the very least needs to manipulate and escape the JSON blob string. For the sake of consistency with the input this could conveniently return a `ddwaf::object`.

Dropping the JSON parser dependency would then be possible.

**Comment by Anilm3** [comment]
https://github.com/DataDog/libddwaf/pull/162
