### ISSUE TITLE
Not building on Mac OS X 

### ISSUE THREAD

**Issue by aymondebroglie** [DataDog/libddwaf#48]
Hello,
I have been maintaining the conda feedstock of ddtrace here https://github.com/conda-forge/ddtrace-feedstock.

And the latest version of ddtrace ( v0.58.* ) is not building for Mac OS. For instance see a log [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=459148&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00&l=548)[](https://user-images.githubusercontent.com/10114614/153900550-9ec9e2a8-2e0f-4661-90eb-3e834ac9dbda.png).
The reason is that the TARGET_OS_OSX env variable is not defined.

image

I have been looking at the issue and it seems that is because the building of [re2](https://github.com/google/re2) fails when building [libddwaf](https://github.com/DataDog/libddwaf).

It seems that the re2 problem has been fixed already see [this commit](https://github.com/google/re2/commit/0d39decb2f0adcbcb943fd31943fcd20398ebe4e) so I think fixing the issue might be a matter of updating dependencies.

I have also opened an issue in ddtrace [here](https://github.com/DataDog/dd-trace-py/issues/3260) 
Thanks !

**Comment by Anilm3** [comment]
Hello,

Thanks for reporting this. We have release version v1.0.18 which basically contains an updated RE2 as per your comment so it should be available to you in the next release of the python tracer, as of writing there is a [release candidate](https://github.com/DataDog/dd-trace-py/releases/tag/v0.59.0rc1) if that is something you'd like to try.

**Comment by aymondebroglie** [comment]
Yes the new version of ddtrace now build on Mac Os thanks !
